{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import bokeh\n",
    "import json\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests\n",
    "from bokeh.plotting import figure, output_file, show, output_notebook\n",
    "from bokeh.models import NumeralTickFormatter\n",
    "from bokeh.io import show\n",
    "from bokeh.layouts import column\n",
    "from bokeh.models import ColumnDataSource, CustomJS, Select\n",
    "from bokeh.plotting import figure\n",
    "from ARCTIC import hdf5_interface\n",
    "from ARCTIC import nrel_api_interface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>location</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ambler-Shungnak-Kobuk</td>\n",
       "      <td>66.995834</td>\n",
       "      <td>-157.377096</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anchorage</td>\n",
       "      <td>61.193625</td>\n",
       "      <td>-149.694974</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Bethel</td>\n",
       "      <td>60.794938</td>\n",
       "      <td>-161.770716</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Chickaloon</td>\n",
       "      <td>61.823570</td>\n",
       "      <td>-148.450442</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Deering</td>\n",
       "      <td>66.069413</td>\n",
       "      <td>-162.766760</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Denali Park</td>\n",
       "      <td>63.537277</td>\n",
       "      <td>-150.985453</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Fairbanks</td>\n",
       "      <td>64.838033</td>\n",
       "      <td>-147.668970</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Fort Yukon</td>\n",
       "      <td>66.571563</td>\n",
       "      <td>-145.250173</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Galena-Koyukuk-Ruby</td>\n",
       "      <td>64.782991</td>\n",
       "      <td>-156.744933</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Homer</td>\n",
       "      <td>59.652521</td>\n",
       "      <td>-151.536496</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Naknek</td>\n",
       "      <td>58.728349</td>\n",
       "      <td>-157.017444</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Noatak</td>\n",
       "      <td>67.570921</td>\n",
       "      <td>-162.967490</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Noorvik</td>\n",
       "      <td>66.836039</td>\n",
       "      <td>-161.041913</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Soldotna</td>\n",
       "      <td>60.486370</td>\n",
       "      <td>-151.060702</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Valdez</td>\n",
       "      <td>61.128663</td>\n",
       "      <td>-146.353366</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Wasilla-Palmer</td>\n",
       "      <td>61.582242</td>\n",
       "      <td>-149.441001</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 location   latitude   longitude\n",
       "0   Ambler-Shungnak-Kobuk  66.995834 -157.377096\n",
       "1               Anchorage  61.193625 -149.694974\n",
       "2                  Bethel  60.794938 -161.770716\n",
       "3              Chickaloon  61.823570 -148.450442\n",
       "4                 Deering  66.069413 -162.766760\n",
       "5             Denali Park  63.537277 -150.985453\n",
       "6               Fairbanks  64.838033 -147.668970\n",
       "7              Fort Yukon  66.571563 -145.250173\n",
       "8     Galena-Koyukuk-Ruby  64.782991 -156.744933\n",
       "9                   Homer  59.652521 -151.536496\n",
       "10                 Naknek  58.728349 -157.017444\n",
       "11                 Noatak  67.570921 -162.967490\n",
       "12                Noorvik  66.836039 -161.041913\n",
       "13               Soldotna  60.486370 -151.060702\n",
       "14                 Valdez  61.128663 -146.353366\n",
       "15         Wasilla-Palmer  61.582242 -149.441001"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "location_dataframe = pd.DataFrame(columns=['location','latitude','longitude'])\n",
    "location_dataframe['location']=['Ambler-Shungnak-Kobuk','Anchorage','Bethel','Chickaloon',\n",
    "                       'Deering','Denali Park','Fairbanks','Fort Yukon',\n",
    "                       'Galena-Koyukuk-Ruby', 'Homer','Naknek','Noatak',\n",
    "                       'Noorvik','Soldotna','Valdez','Wasilla-Palmer']\n",
    "\n",
    "location_dataframe['latitude']=[66.995834, 61.193625, 60.794938, 61.823570,\n",
    "                       66.069413, 63.537277, 64.838033, 66.571563,\n",
    "                       64.782991, 59.652521, 58.728349, 67.570921,\n",
    "                       66.836039, 60.486370, 61.128663, 61.582242]\n",
    "\n",
    "\n",
    "location_dataframe['longitude']=[ -157.377096, -149.694974, -161.770716, -148.450442,\n",
    "                        -162.766760,  -150.985453, -147.668970,  -145.250173,\n",
    "                        -156.744933, -151.536496, -157.017444, -162.967490,\n",
    "                         -161.041913, -151.060702, -146.353366, -149.441001]\n",
    "\n",
    "\n",
    "location_dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "def tilt_angle_plot_generation(location_dataframe): \n",
    "    \"\"\"This function takes in a dataframe that contains latitudes and longitudes for a number of \n",
    "    locations and generates interactive Bokeh plots showing the variation of monthly production \n",
    "    with changing tilt angles.\"\"\"\n",
    "    #The below list is sufficiently granular to cover most situations.\n",
    "    tilt_list = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]\n",
    "\n",
    "    #Walk through each row in the location dataframe, calling PVwatts and plotting results.\n",
    "    for j in range(len(location_dataframe.index)):\n",
    "        print(\"Data for \" + str(location_dataframe['location'][j]) + \" is being calculated\")\n",
    "        nrel_long_tilt = []\n",
    "        for i in range(len(tilt_list)):\n",
    "            json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n",
    "                                                                                     longitude = location_dataframe['longitude'][j], \n",
    "                                                                                     tilt = tilt_list[i], dataset = 'tmy3')\n",
    "            nrel_long_tilt.append(new_dataframe)\n",
    "        tilt_response_dataframe = pd.DataFrame(columns = tilt_list)\n",
    "        for i, tilt in enumerate(tilt_list):\n",
    "            tilt_response_dataframe[tilt] = nrel_long_tilt[i]['ac_monthly']/4\n",
    "\n",
    "        #The below is all of the data for the plotting components.\n",
    "        #This adjusts the name of the saved file, so it's specific to each location.\n",
    "        output_file(\"{}_monthly_production_varying_tilts.html\".format(location_dataframe['location'][j]))\n",
    "        #Set up a month proxy\n",
    "        x = np.arange(1,13)\n",
    "\n",
    "        #Tell the plot where to look for the data. The extra specifications of y values\n",
    "        #enable the plot to be interactive.\n",
    "        source = ColumnDataSource(data=dict(x=x, y=tilt_response_dataframe[5],\n",
    "                                            tilt_5_degrees=tilt_response_dataframe[5], tilt_10_degrees=tilt_response_dataframe[10],\n",
    "                                            tilt_15_degrees=tilt_response_dataframe[15], tilt_20_degrees=tilt_response_dataframe[20],\n",
    "                                            tilt_25_degrees=tilt_response_dataframe[25], tilt_30_degrees=tilt_response_dataframe[30],\n",
    "                                            tilt_35_degrees=tilt_response_dataframe[35], tilt_40_degrees=tilt_response_dataframe[40],\n",
    "                                            tilt_45_degrees=tilt_response_dataframe[45], tilt_50_degrees=tilt_response_dataframe[50],\n",
    "                                            tilt_55_degrees=tilt_response_dataframe[55], tilt_60_degrees=tilt_response_dataframe[60],\n",
    "                                            tilt_65_degrees=tilt_response_dataframe[65], tilt_70_degrees=tilt_response_dataframe[70],\n",
    "                                            tilt_75_degrees=tilt_response_dataframe[75], tilt_80_degrees=tilt_response_dataframe[80],\n",
    "                                            tilt_85_degrees=tilt_response_dataframe[85], tilt_90_degrees=tilt_response_dataframe[90],\n",
    "                                           ))\n",
    "        #Plot specifications\n",
    "        plot = figure(x_axis_label='Month', y_axis_label='Normalized Monthly Production (kWh/kW)', plot_height=400)\n",
    "        plot.line(x='x', y='y', source=source)\n",
    "        plot.title.text = \"Annual Production at Varying Tilt Angles\"\n",
    "        plot.title.align = \"center\"\n",
    "        plot.title.text_font = \"times\"\n",
    "        plot.title.text_font_style = \"italic\"\n",
    "        plot.title.text_font_size = '15pt'\n",
    "        #This line is what connects the changing dropdown menu with the data that is displayed.\n",
    "        select = Select(value='foo', options=['tilt_5_degrees', 'tilt_10_degrees','tilt_15_degrees',\n",
    "                                             'tilt_20_degrees','tilt_25_degrees','tilt_30_degrees',\n",
    "                                             'tilt_35_degrees','tilt_40_degrees','tilt_45_degrees',\n",
    "                                             'tilt_50_degrees','tilt_55_degrees','tilt_60_degrees',\n",
    "                                             'tilt_65_degrees','tilt_70_degrees','tilt_75_degrees',\n",
    "                                             'tilt_80_degrees','tilt_85_degrees','tilt_90_degrees'])\n",
    "        #javascript that actually makes the changes possible.\n",
    "        select.js_on_change('value', CustomJS(args=dict(source=source, select=select), code=\"\"\"\n",
    "            // make a shallow copy of the current data dict\n",
    "            const new_data = Object.assign({}, source.data)\n",
    "\n",
    "            // update the y column in the new data dict from the appropriate other column\n",
    "            new_data.y = source.data[select.value]\n",
    "\n",
    "            // set the new data on source, BokehJS will pick this up automatically\n",
    "            source.data = new_data\n",
    "        \"\"\"))\n",
    "\n",
    "        show(column(plot, select))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data for Ambler-Shungnak-Kobuk is being calculated\n",
      "Data for Anchorage is being calculated\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    376\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# Python 2.7, use buffering of HTTP responses\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 377\u001b[1;33m                 \u001b[0mhttplib_response\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbuffering\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    378\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# Python 3\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: getresponse() got an unexpected keyword argument 'buffering'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-53-6535c7c48afc>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mtilt_angle_plot_generation\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlocation_dataframe\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-52-cf929fb705a2>\u001b[0m in \u001b[0;36mtilt_angle_plot_generation\u001b[1;34m(location_dataframe)\u001b[0m\n\u001b[0;32m     13\u001b[0m             json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n\u001b[0;32m     14\u001b[0m                                                                                      \u001b[0mlongitude\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlocation_dataframe\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'longitude'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mj\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 15\u001b[1;33m                                                                                      tilt = tilt_list[i], dataset = 'tmy3')\n\u001b[0m\u001b[0;32m     16\u001b[0m             \u001b[0mnrel_long_tilt\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnew_dataframe\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     17\u001b[0m         \u001b[0mtilt_response_dataframe\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mDataFrame\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mcolumns\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtilt_list\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\documents\\direct classes\\alaska_project\\acep_solar\\ARCTIC\\nrel_api_interface.py\u001b[0m in \u001b[0;36mcall_pvwatts\u001b[1;34m(latitude, longitude, tilt, dataset, azimuth)\u001b[0m\n\u001b[0;32m     50\u001b[0m                   \u001b[1;34m\"module_type\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"losses\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m14.08\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"array_type\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"tilt\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mtilt\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"azimuth\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mazimuth\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     51\u001b[0m                   \"lat\": latitude, \"lon\": longitude, \"dataset\": dataset}\n\u001b[1;32m---> 52\u001b[1;33m     \u001b[0mpvwatts_response\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"https://developer.nrel.gov/api/pvwatts/v6\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mparameters\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     53\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     54\u001b[0m     \u001b[1;31m#Check the response from pvwatts to ensure that data was actually received\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(url, params, **kwargs)\u001b[0m\n\u001b[0;32m     73\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     74\u001b[0m     \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'allow_redirects'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 75\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'get'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     76\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(method, url, **kwargs)\u001b[0m\n\u001b[0;32m     58\u001b[0m     \u001b[1;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     59\u001b[0m     \u001b[1;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 60\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     61\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     62\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    531\u001b[0m         }\n\u001b[0;32m    532\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 533\u001b[1;33m         \u001b[0mresp\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    534\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    535\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    644\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    645\u001b[0m         \u001b[1;31m# Send the request\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 646\u001b[1;33m         \u001b[0mr\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    647\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    648\u001b[0m         \u001b[1;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\requests\\adapters.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    447\u001b[0m                     \u001b[0mdecode_content\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    448\u001b[0m                     \u001b[0mretries\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmax_retries\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 449\u001b[1;33m                     \u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    450\u001b[0m                 )\n\u001b[0;32m    451\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    598\u001b[0m                                                   \u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtimeout_obj\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    599\u001b[0m                                                   \u001b[0mbody\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 600\u001b[1;33m                                                   chunked=chunked)\n\u001b[0m\u001b[0;32m    601\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    602\u001b[0m             \u001b[1;31m# If we're going to release the connection in ``finally:``, then\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    378\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# Python 3\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    379\u001b[0m                 \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 380\u001b[1;33m                     \u001b[0mhttplib_response\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    381\u001b[0m                 \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    382\u001b[0m                     \u001b[1;31m# Remove the TypeError from the exception chain in Python 3;\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1329\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1330\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1331\u001b[1;33m                 \u001b[0mresponse\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1332\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1333\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36mbegin\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    295\u001b[0m         \u001b[1;31m# read until we get a non-100 response\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    296\u001b[0m         \u001b[1;32mwhile\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 297\u001b[1;33m             \u001b[0mversion\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    298\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    299\u001b[0m                 \u001b[1;32mbreak\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36m_read_status\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    256\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    257\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_read_status\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 258\u001b[1;33m         \u001b[0mline\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreadline\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0m_MAXLINE\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"iso-8859-1\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    259\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mline\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m>\u001b[0m \u001b[0m_MAXLINE\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    260\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mLineTooLong\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"status line\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\socket.py\u001b[0m in \u001b[0;36mreadinto\u001b[1;34m(self, b)\u001b[0m\n\u001b[0;32m    584\u001b[0m         \u001b[1;32mwhile\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    585\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 586\u001b[1;33m                 \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    587\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    588\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_timeout_occurred\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\urllib3\\contrib\\pyopenssl.py\u001b[0m in \u001b[0;36mrecv_into\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    292\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mrecv_into\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    293\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 294\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnection\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    295\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[0mOpenSSL\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSSL\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSysCallError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    296\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msuppress_ragged_eofs\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0margs\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;33m(\u001b[0m\u001b[1;33m-\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'Unexpected EOF'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Miniconda3\\lib\\site-packages\\OpenSSL\\SSL.py\u001b[0m in \u001b[0;36mrecv_into\u001b[1;34m(self, buffer, nbytes, flags)\u001b[0m\n\u001b[0;32m   1819\u001b[0m             \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_lib\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSSL_peek\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_ssl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbuf\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnbytes\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1820\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1821\u001b[1;33m             \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_lib\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSSL_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_ssl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbuf\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnbytes\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1822\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_raise_ssl_error\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_ssl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1823\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "tilt_angle_plot_generation(location_dataframe)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Begin tilt vs annual production graphic generation.\n",
    "def annual_tilt_angle_plot_generation(location_dataframe):\n",
    "    \"\"\"This function plots the annual generation predicted by PVWatts for TMY2 and TMY3 datasets\n",
    "    at a variety of tilt angles. It operates dynamically, and prints for all locations in the \n",
    "    passed location dataframe.\"\"\"\n",
    "    #The below list is sufficiently granular to cover most situations.\n",
    "    tilt_list = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]\n",
    "    \n",
    "    #Walk through each row in the location dataframe, calling PVwatts and plotting results.\n",
    "    for j in range(len(location_dataframe.index)):\n",
    "        print(\"Data for \" + str(location_dataframe['location'][j]) + \" is being calculated\")\n",
    "        #If the response from PVWatts has an error, flip the zero to a one, and don't plot.\n",
    "        tmy2_response = np.zeros(len(tilt_list))\n",
    "        tmy3_response = np.zeros(len(tilt_list))\n",
    "        annual_production_tmy2 = []\n",
    "        annual_production_tmy3 = []\n",
    "        #Calculate all of the tilt information for TMY3 and TMY3. \n",
    "        for i in range(len(tilt_list)):\n",
    "            json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n",
    "                                                                                     longitude = location_dataframe['longitude'][j], \n",
    "                                                                                     tilt = tilt_list[i], dataset = 'tmy3')\n",
    "            if json_response['errors'] != []:\n",
    "                tmy3_response[i] = 1\n",
    "            else:\n",
    "                annual_production_tmy3.append(new_dataframe['ac_annual'][2]/4)\n",
    "            \n",
    "            #repeat the above with the TMY2 dataset\n",
    "            json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n",
    "                                                                                 longitude = location_dataframe['longitude'][j], \n",
    "                                                                                 tilt = tilt_list[i], dataset = 'tmy2')\n",
    "            if json_response['errors'] != []:\n",
    "                tmy2_response[i] = 1\n",
    "            else:    \n",
    "                annual_production_tmy2.append(new_dataframe['ac_annual'][2]/4)\n",
    "        \n",
    "        #Save the file\n",
    "        output_file(\"{}_annual_production_varying_tilts.html\".format(location_dataframe['location'][j]))\n",
    "        p = figure( x_axis_label='Tilts', y_axis_label='Annual Production (kWh)',plot_width=500, plot_height=250)\n",
    "\n",
    "        # add a line renderer\n",
    "        #Check to see if there is TMY2 or TMY3 data for this location. \n",
    "        if sum(tmy2_response) == 0:\n",
    "            p.line(tilt_list, annual_production_tmy2, line_width=2, color='red', legend='TMY2')\n",
    "        else:\n",
    "            print(\"No TMY2 data was available for this location.\")\n",
    "        if sum(tmy3_response) == 0:    \n",
    "            p.line(tilt_list, annual_production_tmy3, line_width=2, color='blue', legend='TMY3')\n",
    "        else:\n",
    "            print(\"No TMY3 data was available for this location\")\n",
    "\n",
    "        p.xaxis.ticker = [10,20,30,40,50,60,70,80,90]\n",
    "        p.title.text = \"Annual Production at Varying Tilts\"\n",
    "        p.title.align = \"center\"\n",
    "        p.title.text_font = \"times\"\n",
    "        p.title.text_font_style = \"italic\"\n",
    "        p.title.text_font_size = '12pt'\n",
    "\n",
    "        show(p)           "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data for Ambler-Shungnak-Kobuk is being calculated\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "No TMY2 data was available for this location.\n",
      "Data for Anchorage is being calculated\n",
      "Data for Bethel is being calculated\n",
      "Data for Chickaloon is being calculated\n",
      "Data for Deering is being calculated\n",
      "Data for Denali Park is being calculated\n",
      "Data for Fairbanks is being calculated\n",
      "Data for Fort Yukon is being calculated\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.571563 lon=-145.250173']\n",
      "Please correct the error and call this function again.\n",
      "No TMY2 data was available for this location.\n",
      "Data for Galena-Koyukuk-Ruby is being calculated\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=64.782991 lon=-156.744933']\n",
      "Please correct the error and call this function again.\n",
      "No TMY2 data was available for this location.\n",
      "Data for Homer is being calculated\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=59.652521 lon=-151.536496']\n",
      "Please correct the error and call this function again.\n",
      "No TMY2 data was available for this location.\n",
      "Data for Naknek is being calculated\n",
      "Data for Noatak is being calculated\n",
      "Data for Noorvik is being calculated\n",
      "Data for Soldotna is being calculated\n",
      "Data for Valdez is being calculated\n",
      "Data for Wasilla-Palmer is being calculated\n"
     ]
    }
   ],
   "source": [
    "annual_tilt_angle_plot_generation(location_dataframe)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "def annual_production_loss_plot_generation(location_dataframe):\n",
    "    \"\"\"This function plots the percentage loss of production for tilt angles that are not\n",
    "    in alignment with the optimal tilt angle.\"\"\"    \n",
    "    #The below list is sufficiently granular to cover most situations.\n",
    "    tilt_list = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]\n",
    "    \n",
    "    #Walk through each row in the location dataframe, calling PVwatts and plotting results.\n",
    "    for j in range(len(location_dataframe.index)):\n",
    "        print(\"Data for \" + str(location_dataframe['location'][j]) + \" is being calculated\")\n",
    "        #If the response from PVWatts has an error, flip the zero to a one, and don't plot.\n",
    "        tmy2_response = np.zeros(len(tilt_list))\n",
    "        tmy3_response = np.zeros(len(tilt_list))\n",
    "        annual_production_tmy2 = []\n",
    "        annual_production_tmy3 = []\n",
    "        #Calculate all of the tilt information for TMY3 and TMY3. \n",
    "        for i in range(len(tilt_list)):\n",
    "            json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n",
    "                                                                                     longitude = location_dataframe['longitude'][j], \n",
    "                                                                                     tilt = tilt_list[i], dataset = 'tmy3')\n",
    "            if json_response['errors'] != []:\n",
    "                tmy3_response[i] = 1\n",
    "            else:\n",
    "                annual_production_tmy3.append(new_dataframe['ac_annual'][2]/4)\n",
    "            \n",
    "            #repeat the above with the TMY2 dataset\n",
    "            json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n",
    "                                                                                 longitude = location_dataframe['longitude'][j], \n",
    "                                                                                 tilt = tilt_list[i], dataset = 'tmy2')\n",
    "            if json_response['errors'] != []:\n",
    "                tmy2_response[i] = 1\n",
    "            else:    \n",
    "                annual_production_tmy2.append(new_dataframe['ac_annual'][2]/4)\n",
    "        \n",
    "        if sum(tmy2_response) == 0:\n",
    "            dict_tmy2 = {'Tilts':tilt_list,'Annual_production':annual_production_tmy2}\n",
    "            df_tmy2 = pd.DataFrame(dict_tmy2)\n",
    "            #Then find out the max production row\n",
    "            max_tilt_tmy2 = int(df_tmy2[['Annual_production']].idxmax().values)\n",
    "            #Then calculate the other tilts' percent loss compared with the max annual production\n",
    "            lose_tmy2 = []\n",
    "            for index, row in df_tmy2.iterrows():\n",
    "                tilt_loss = 1- row['Annual_production']/df_tmy2['Annual_production'][max_tilt_tmy2]\n",
    "                lose_tmy2.append(tilt_loss)\n",
    "            df_tmy2['loss']=lose_tmy2\n",
    "\n",
    "        else:\n",
    "            print(\"There is no TMY2 weather station data at this location.\")\n",
    "            \n",
    "        #Repeat for TMY3 data.\n",
    "        if sum(tmy3_response) == 0:\n",
    "            dict_tmy3 = {'Tilts':tilt_list,'Annual_production':annual_production_tmy3}\n",
    "            df_tmy3 = pd.DataFrame(dict_tmy3)\n",
    "            max_tilt_tmy3 = int(df_tmy3[['Annual_production']].idxmax().values)\n",
    "            lose_tmy3 = []\n",
    "            for index, row in df_tmy3.iterrows():\n",
    "                tilt_loss = 1- row['Annual_production']/df_tmy3['Annual_production'][max_tilt_tmy3]\n",
    "                lose_tmy3.append(tilt_loss)\n",
    "            df_tmy3['loss']=lose_tmy3   \n",
    "\n",
    "        #Save the file\n",
    "        output_file(\"{}_annual_production_loss_tilts.html\".format(location_dataframe['location'][j]))\n",
    "\n",
    "        p = figure(x_axis_label='Tilts', y_axis_label='loss (%)',plot_width=500, plot_height=250)\n",
    "\n",
    "        # add a line renderer\n",
    "        if sum(tmy2_response) == 0:\n",
    "            p.line(tilt_list, df_tmy2['loss'], line_width=2,color='red',legend=\"TMY2\")\n",
    "        if sum(tmy3_response) == 0:\n",
    "            p.line(tilt_list, df_tmy3['loss'],line_width=2,color='blue',legend=\"TMY3\")\n",
    "        p.xaxis.ticker = [10,20,30,40,50,60,70,80,90]\n",
    "        p.yaxis.formatter = NumeralTickFormatter(format='0 %')\n",
    "        p.title.text = \"Annual Production Loss with Varying Tilts\"\n",
    "        p.title.align = \"center\"\n",
    "        p.title.text_font = \"times\"\n",
    "        p.title.text_font_style = \"italic\"\n",
    "        p.title.text_font_size = '12pt'\n",
    "\n",
    "        show(p)    \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data for Ambler-Shungnak-Kobuk is being calculated\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "Warning! PVWatts had an error 422. This means either the solar dataset does not exist for \n",
      "your intended location, or that something was wrong with your inputs (out of bounds possibly).\n",
      "Warning! An error occured when calling PVWatts. The error was: \n",
      "['No climate data found with dataset=tmy2 for location specified: lat=66.995834 lon=-157.377096']\n",
      "Please correct the error and call this function again.\n",
      "There is no TMY2 weather station data at this location.\n",
      "Data for Anchorage is being calculated\n",
      "Data for Bethel is being calculated\n",
      "Data for Chickaloon is being calculated\n",
      "Data for Deering is being calculated\n",
      "Data for Denali Park is being calculated\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "Error: 429",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-19-61571702a831>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mannual_production_loss_plot_generation\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlocation_dataframe\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-18-c0310cf717b1>\u001b[0m in \u001b[0;36mannual_production_loss_plot_generation\u001b[1;34m(location_dataframe)\u001b[0m\n\u001b[0;32m     26\u001b[0m             json_response, new_dataframe = nrel_api_interface.call_pvwatts(latitude = location_dataframe['latitude'][j], \n\u001b[0;32m     27\u001b[0m                                                                                  \u001b[0mlongitude\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlocation_dataframe\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'longitude'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mj\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 28\u001b[1;33m                                                                                  tilt = tilt_list[i], dataset = 'tmy2')\n\u001b[0m\u001b[0;32m     29\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mjson_response\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'errors'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     30\u001b[0m                 \u001b[0mtmy2_response\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mi\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\documents\\direct classes\\alaska_project\\acep_solar\\ARCTIC\\nrel_api_interface.py\u001b[0m in \u001b[0;36mcall_pvwatts\u001b[1;34m(latitude, longitude, tilt, dataset, azimuth)\u001b[0m\n\u001b[0;32m     53\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     54\u001b[0m     \u001b[1;31m#Check the response from pvwatts to ensure that data was actually received\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 55\u001b[1;33m     \u001b[1;32massert\u001b[0m \u001b[0mpvwatts_response\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m200\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mpvwatts_response\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m422\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"Error: \"\u001b[0m \u001b[1;33m+\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpvwatts_response\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus_code\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     56\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     57\u001b[0m     \u001b[1;31m#Note the 422 response implies something was wrong about inputs.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAssertionError\u001b[0m: Error: 429"
     ]
    }
   ],
   "source": [
    "annual_production_loss_plot_generation(location_dataframe)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
